# ./.github/workflows/workflow.yml
name: MurmeliCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the project repository.
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # Install the desired Java version.
      - name: Prepare java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "zulu"
          java-version: "21"
      # Setup Leiningen. Also supports setting up other commonly used tools.
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@02f5a82b79a547523e664fe8a7a32ea14884d7b2 # 13.6
        with:
          lein: 2.12.0
      # Enable cache so our actions run faster.
      - name: Cache clojure dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.m2/repository
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-
      - name: Test
        run: lein test
      - name: Deploy
        env:
          # Provide environment variables used to deploy.
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: lein deploy clojars
